# python imports
import os
from dotenv import load_dotenv

# local imports
from fuga.api_client import FUGAClient
from fuga.miscellaneous import FUGAMisc

# set variables
load_dotenv()  # Load environment variables from .env file
API_URL = os.getenv("API_URL")
USERNAME = os.getenv("USERNAME")
PASSWORD = os.getenv("PASSWORD")

# Initialize the FUGA API client
client = FUGAClient(API_URL, USERNAME, PASSWORD)
client.login()

path = "/error_messages/metadata"

res = client.request("GET", path)

print(f"Response: {res}")


errors = {
    "ACQUISITION_TYPE_MUST_BE_OWNERSHIP_OR_LICENSE": "The acquisition must have a type of OWNERSHIP or LICENSE",
    "AGGREGATED_ENTITIES_REQUIRED": "Aggregated entities required",
    "ALL_AUDIO_ASSETS_MUST_HAVE_AT_LEAST_ONE_24_BIT_ENCODING": "All audio assets must have at least one 24 bit file if Product is mastered for iTunes",
    "ALL_AUDIO_ASSETS_MUST_HAVE_EMAIL_ADDRESS": "All audio assets must have a master studio email address if Product is mastered for iTunes",
    "ALL_VOLUMES_MUST_HAVE_AT_LEAST_ONE_ASSET": "All volumes must have at least one asset.",
    "AMOUNT_CANNOT_BE_NEGATIVE": "Amount cannot be negative {0}.",
    "ARTIST_IDENTIFIER_REQUIRED": "{0} artist identifiers missing for {1}",
    "ARTIST_IN_ASSET_MAY_NOT_BE_VARIOUS": "Artist or featuring artist in asset may not be called {0} when the duration is less than 25 minutes.",
    "ARTIST_INVALID_IDENTIFIER": "The provided DSP Artist Identifier does not have the correct format. {0}",
    "ARTIST_NOT_FOUND": "No artist with ID {0} was found.",
    "ASSET_DOES_NOT_HAVE_REQUIRED_ENCODING": "This asset does not have the required encoding.",
    "ASSET_DURATION_SHORT": "Duration of the recording attached to this asset is {0} seconds, while at least {1} is expected.",
    "ASSET_MUST_HAVE_ADM_ENCODING": "Apple Digital Master file is required for this asset",
    "ASSETS_DO_NOT_HAVE_VALID_RIGHTSHOLDERS": "None of the assets contains valid rights holders to deliver to PRO '{0}'.",
    "ASSETS_PRODUCT_IS_NOT_MARKED_AS_EXPLICIT": "Product with UPC {0} is not explicit but the asset in sequence {1} is.",
    "AUDIO_FILE_CORRUPT": "The audiofile {0} has anomalies at these points: {1} and possibly more",
    "BARCODE_RANGE_CANNOT_BE_EMPTY": "Barcode range {0}-{1} should contain at least one barcode.",
    "BARCODE_RANGE_INVALID_LENGTH": "Invalid value {0} for type {1} in barcode range.",
    "BARCODE_RANGE_OVERLAP": "Barcode ranges cannot be overlapped: new barcode range {0}-{1} overlaps with existing barcode ranges.",
    "BARCODES_DEPLETED": "There are no more available barcodes, please contact our support team",
    "BENEFICIARY_AND_SUBJECT_MUST_BE_DIFFERENT": "On granting/revoking rights, beneficiary and subject must always be different.",
    "CAN_ONLY_PUSH_NEW_OPERATIONS": "Can only push new bulk operations into the queue.",
    "CANNOT_ACCEPT_ALBUM": "Product cannot be accepted b/c it hasn't been (re-)delivered yet or is accepted already",
    "CANNOT_ACCEPT_CHANGED_TRACK_LIST": "Can not accept a track list change",
    "CANNOT_ACCEPT_EXISTING": "Can not accept a product that already exists in the catalog",
    "CANNOT_ACCEPT_NOT_SUBMITTED_ITEM": "Cannot accept a {0} item",
    "CANNOT_ACCEPT_UNAPPROVED_ITEM": "A submitted product that has not been accepted by the super organization cannot be accepted by a member of the Fuga QC.",
    "CANNOT_ACCEPT_UNPUBLISHABLE": "Can not accept a not publishable product",
    "CANNOT_ATTACH_ASSET_TO_PRODUCT_IN_USE": "Cannot attach an asset to a product that has been published or delivered.",
    "CANNOT_ATTACH_ASSET_TYPE_TO_PRODUCT": "Assets of type {0} cannot be attached to products of type {1}",
    "CANNOT_CANCEL_FINISHED_OPERATION": "Finished operations cannot be canceled.",
    "CANNOT_CLONE_SOURCED_PRODUCT": "Sourced products may not be cloned.",
    "CANNOT_DELETE_ACQUIRED_ALBUM": "Delivered products can only be rejected, not deleted.",
    "CANNOT_DELETE_ATTACHED_ASSET": "This asset is used by one or more products.  Detach it from the other products before deleting.",
    "CANNOT_DELETE_CONTRACT_WITH_DELIVERIES": "You can only delete contracts on which no deliveries have yet been made.",
    "CANNOT_DELETE_DEFAULT_USAGE_RIGHT": "Default Usage Rights cannot be deleted.",
    "CANNOT_DELETE_EMPLOYED_USER": "This user cannot be deleted as it is an employee of an organization.",
    "CANNOT_DELETE_GENRE": "Genres are fixed in the database and may not be deleted.",
    "CANNOT_DELETE_ITEM_IN_USE": "This item cannot be deleted as it is in use.",
    "CANNOT_DELETE_LABEL": "This label cannot be deleted because it is used in a product or asset.",
    "CANNOT_DELETE_ORGANIZATION_WITH_CONTRACTS": "This organization cannot be deleted as it still contains associated contracts.",
    "CANNOT_DELETE_ORGANIZATION_WITH_EMPLOYEES": "This organization cannot be deleted as it still contains associated employees.",
    "CANNOT_DELETE_RELEASE_SCHEDULE": "Cannot delete the {0} release schedule",
    "CANNOT_DELETE_TRACK_FROM_DELIVERED_PRODUCT": "You cannot delete an asset from a delivered product.",
    "CANNOT_DELETE_UNFINISHED_OPERATION": "You cannot delete an operation unless it's finished or cancelled.",
    "CANNOT_DELIVER_PRODUCT_WITH_EMPTY_USAGE_RIGHTS": "Cannot deliver a product that has one or more empty usage rights.",
    "CANNOT_DELIVER_UNPUBLISHED_PRODUCT": "Cannot deliver an unpublished product.",
    "CANNOT_DETACH_ASSET_FROM_PRODUCT_IN_USE": "You cannot detach an asset from a product that has been published or delivered.",
    "CANNOT_FIND_ASSET_WITH_ID": "Cannot find asset with ID {0}",
    "CANNOT_FIND_ASSET_WITH_UPC": "Cannot find asset with ISRC of {0} attached to a product with UPC code of {1} ",
    "CANNOT_FIND_ITEM_WITH_ID": "Cannot find {0} with {1} of {2}.",
    "CANNOT_HAVE_ASSET_MAPPING_WITHOUT_ASSET_TIERS": "Cannot have an asset mapping if the rule set does not have an asset tier set",
    "CANNOT_HAVE_MULTIPLE_RUNNING_ATTEMPTS": "Only one running attempt can be associated with a delivery.",
    "CANNOT_HAVE_OVER_HALF_INSTANT_GRATIFICATION": "A maximum of 50% of assets are allowed to be marked as instant gratification.",
    "CANNOT_HAVE_PUBLISHING_HOUSE_WITH_COPYRIGHT_CONTROL": "If you have copyright control, do not enter a publisher.",
    "CANNOT_HAVE_TERRITORY_FILTER_ON_DEFAULT_SCHEDULE": "You can't have a territory filter on the default schedule",
    "CANNOT_MOVE_PRODUCT_TO_OTHER_ORG": "A product may not be moved to the catalog of another organization.",
    "CANNOT_PUBLISH_WITHOUT_DELIVERY_RULE_SETS": "Cannot publish product without delivery rule sets",
    "CANNOT_PUBLISH_WITHOUT_EFFECTIVE_CONTRACT": "Cannot publish product without effective contracts",
    "CANNOT_PUSH_ASSET_TO_DIFFERENT_SUB_ORGANIZATION": "Asset ({0}) already belongs to sub organization '{1}'",
    "CANNOT_PUSH_PRODUCT_TO_DIFFERENT_SUB_ORGANIZATION": "Product ({0}) already belongs to sub organization '{1}'",
    "CANNOT_REDELIVER": "Cannot redeliver product because it is not delivered to DSP",
    "CANNOT_REDELIVER_OVER_NONEFFECTIVE_CONTRACT": "Cannot redeliver over a non-effective contract (From {0} to {1})",
    "CANNOT_REJECT_ALBUM": "Only delivered products may be rejected.",
    "CANNOT_REJECT_ITEM_BEFORE_QC": "Can not reject an item that is not yet rejected by QC",
    "CANNOT_REJECT_ITEM_NOT_IN_QC": "Can not reject an item that is not yet submitted for QC",
    "CANNOT_REJECT_NOT_SUBMITTED_ITEM": "Can not reject a {0} item",
    "CANNOT_REMOVE_FILE_FOR_PUBLISHED_PRODUCT": "Cannot remove all stereo or Dolby Atmos audio from a track that is attached to one or more Published products",
    "CANNOT_SET_ADM_ASSET": "Asset cannot be marked as Apple Digital Master. The feature is not enabled for this organization.",
    "CANNOT_SET_ADM_ENCODING": "Apple Digital Master encoding cannot be attached to this asset. The feature is not enabled for this organization.",
    "CANNOT_SET_ADM_PRODUCT": "Product cannot be marked as Apple Digital Master. The feature is not enabled for this organization.",
    "CANNOT_SET_PREORDER_ONLY_ON_PUBLISHED_PRODUCT": "Pre-order only value cannot be changed after a Product has been published/approved",
    "CANNOT_TAKEDOWN_PRODUCT": "This product cannot be taken down.",
    "CANNOT_UPDATE": "There was a problem saving your update.",
    "CANNOT_UPDATE_BARCODE": "The barcode cannot be changed for a published product",
    "CANNOT_UPDATE_BARCODE_RANGE_IN_USE": "Cannot update barcode range since it is in use",
    "CANNOT_UPDATE_DELIVERED_ASSET_VOLUME_NUMBER": "Volume number cannot be adjusted for a published product",
    "CANNOT_UPDATE_DELIVERED_PRODUCT_N_VOLUMES": "Total number of volumes cannot be adjusted for a published product",
    "CANNOT_UPDATE_DISTRIBUTION_ACQUISITION_TYPE": "Products with an acquisition Type of DEAL cannot be changed to another acquisition Type.",
    "CANNOT_UPDATE_ISRC": "ISRC cannot be changed for a published product",
    "CANNOT_UPDATE_RELEASE_SCHEDULE_STATUS": "Product was already delivered, not possible to update.",
    "CANNOT_UPDATE_TERRITORY_FOR_DISTRIBUTION_AND_OWNERSHIP": "This product's territories can't be updated. Because its acquisition type is Distribution",
    "CATALOG_REQUEST_ALREADY_PENDING": "There is already a catalog request pending for that organisation.",
    "CHANNEL_REQUEST_APPROVAL_ERROR_PRIMARY_ARTIST": "Artist {0} is not attached to the product as a primary artist",
    "CHANNELS_ALREADY_EXIST": "There are already channels present for this artist",
    "CONFIGURATION_ALREADY_EXIST": "Usage configuration already exists",
    "CONSTRAINT_VIOLATION": "That item already exists.",
    "CONSTRAINT_VIOLATION_PRODUCT": "An album with the same title, version, and catalog number already exists in your catalog. Or you are using a UPC code that is already being used for another album.",
    "CONTACT_ALREADY_ESTABLISHED": "You have already established contact with this user. Would you like to login anyway?",
    "CONTRACT_ALREADY_IN_PLACE": "Contract cannot be created because a contract in that direction is already in place.",
    "CONTRACT_CANNOT_BE_FOUND": "The contract could not be found.",
    "CONTRACT_DISTRIBUTION_NOT_IN_PLACE": "There is no effective contract in place between the distributor ({0}) and end point organization ({1}).",
    "CONTRACT_NOT_EFFECTIVE": "It is not possible to deliver this product because the contract is not effective. Make sure that the start and end dates of the contract are correct.",
    "CONTRACT_NOT_EFFECTIVE_BETWEEN_DATES": "The contract was not effective between {0} and {1}.",
    "CONTRIBUTOR_COMPOSER_REQUIRED": "At least 1 contributor with role 'Composer' is required",
    "CONTRIBUTOR_LYRICIST_REQUIRED": "At least 1 contributor with role 'Lyricist' is required as language of performance is not Instrumental",
    "CORRUPTED_DATA": "Corrupted data detected. Not able to proceed.",
    "COVER_ART_MAX_HEIGHT_MUST_BE_A_POSITIVE_VALUE": "Cover art's maximum height must be a positive value.",
    "COVER_ART_MAX_HEIGHT_MUST_BE_GREATER_THAN_MIN_HEIGHT": "Cover art's maximum height must be greater than minimum height's value.",
    "COVER_ART_MAX_WIDTH_MUST_BE_A_POSITIVE_VALUE": "Cover art's maximum width must be a positive value.",
    "COVER_ART_MAX_WIDTH_MUST_BE_GREATER_THAN_MIN_WIDTH": "Cover art's maximum width must be greater than minimum width's value.",
    "CREDITED_PERFORMERS_REQUIRED": "At least one 'Performing Artists'-type contributor/instrument is required.",
    "CREDITED_PRODUCTION_AND_ENGINEERING_REQUIRED": "At least one 'Production & Engineering'-type contributor role is required.",
    "CREDITED_COMPOSITION_AND_LYRICS_REQUIRED": "At least one 'Composition & Lyrics'-type contributor role is required.",
    "CURRENCY_CONVERSION_INVALID": "You cannot add a currency translation for the same currency.",
    "CURRENCY_CONVERSION_NOT_FOUND": "No currency conversion has been defined for the period {0} from the currencies {1} to {2}.",
    "DATE_CANNOT_BE_IN_FUTURE": "Date cannot be a future date: {0}.",
    "DEAL_CANNOT_BE_FOUND": "The deal with the passed ID could not be found.",
    "DEALED_ALBUM_REQUIRED": "The downstream party does not yet have a copy of that asset or product.",
    "DELETE_FAILED": "Delete failed.",
    "DELIVERY_ATTEMPT_NOT_FOUND": "The delivery attempt with the passed ID could not be found.",
    "DELIVERY_DUPLICATE_FOR_PRODUCT_AND_ORGANIZATION": "You have delivered this product over another contract to the same organization. Please take it down before delivering it over a new contract.",
    "DELIVERY_NOT_FOUND": "The delivery with the passed ID could not be found.",
    "DELIVERY_NOT_IN_MANUAL_STATE": "In order for a delivery to be finished, it needs to be marked as MANUAL. If this is not the case, it is not possible to finish the delivery.",
    "DELIVERY_WAS_NOT_FETCHED": "When manually setting a delivery to processing, it needs to have been previously fetched.",
    "DOWNSTREAM_CANNOT_ACCEPT_PRODUCT": "The downstream party does not accept products of this type.",
    "DOWNSTREAM_PRODUCT_NOT_YET_DELIVERED": "Downstream product is not delivered. So cannot perform takedown operation on the product.",
    "DSP_GROUP_HAS_BEEN_DELETED": "This group has been already deleted",
    "DSP_IDENTIFIER_REQUIRED": "DSP Artist Identifiers cannot be empty",
    "DUPLICATE_APPLICATION_FEATURE_SETTING": "Feature setting for {0} already exists.",
    "DUPLICATE_APPLICATION_FEATURE_SETTING_OVERRIDE": "Feature setting override for {0} and organization {1} already exists.",
    "DUPLICATE_ARTIST_NAME": "Artist name {0} already exists.",
    "DUPLICATE_ARTIST_NAME_PROPRIETARY_ID": "Artist name {0} already exists. Please provide a valid proprietary id.",
    "DUPLICATE_AUDIOPRODUCT": "An audioproduct with name {1}, version {0}, catalog number {2} and state {3} already exists in your catalog.",
    "DUPLICATE_CHANNEL_REQUEST": "A pending channel request for this artist already exists",
    "DUPLICATE_CONTRIBUTOR": "The combination of role {0} and contributor {1} already exists for this asset.",
    "DUPLICATE_DSP_GROUP": "DSP Group {0} already exists.",
    "DUPLICATE_ISRC_CODE": "Another asset, called {0} (ID: {1}), already uses ISRC {2}. Please enter a unique ISRC",
    "DUPLICATE_ISRC_CODE_WITHIN_SAME_ASSET": "The same ISRC cannot be used twice on the same asset",
    "DUPLICATE_LABEL_NAME": "Label name {0} already exists.",
    "DUPLICATE_ORGANIZATION_NAME": "An Organization with the same name already exists in the system. Please choose another organization name.",
    "DUPLICATE_PERSON_NAME": "Person name {0} already exists.",
    "DUPLICATE_PUBLISHER": "Publisher with Composer/Lyricist {0} and Publisher {1} already exists for this asset.",
    "DUPLICATE_PUBLISHINGHOUSE_NAME": "Publisher {0} already exists.",
    "DUPLICATE_RECORDING": "There {0, choice, 1#is one asset|1<are {0} assets} with the same recording: {2} {1, choice, 0#|0<and {1} more}",
    "DUPLICATE_SUBGENRE_NAME": "Subgenre {0} already exists.",
    "DUPLICATE_TREND_REPORT_RETRIEVAL_SCHEDULE": "Trend Report Retrieval Schedule with organization id: {0}, dsp id: {1} and 'Active' status already exists in the system. Please inactivate / delete existing record before proceeding.",
    "DUPLICATE_UPC_CODE": "A product with UPC code {0} already exists in your catalog.",
    "DUPLICATE_USER_NAME": "User with name {0} already exists in the system. Please choose another username.",
    "DUPLICATED_TRANSLATION_FOR_FIELD_AND_LANGUAGE": "This translation already exists for entity id {0}, language {1} and field {2}",
    "EMAIL_ADDRESS_NOT_FOUND": "We are sorry, that email address was not found in our database.",
    "EMBEDDED_COMMAND_NOT_FOUND": "The invitation is no longer outstanding! It has either been redeemed at an earlier stage or did not exist in the first place.",
    "ENCODING_COMPLETE_WITHOUT_FILE": "The encoding was completed, but there is no encoded file present",
    "ENCODING_REQUESTED_WITHOUT_FILE": "The encoding was requested, but there is no file present ",
    "ENTITY_ALREADY_HAS_ISRC": "{0} already has an ISRC assigned",
    "ENTITY_LOCKED": "Entity could not be updated because it was locked by another transaction",
    "ENTITY_NOT_FOUND": "Could not find {0} with ID {1}.",
    "EXCEEDING_MAXIMUM_PERCENTAGE": "The sum of all percentages can not exceed 100 percent.",
    "EXISTING_DELIVERY_IS_PROCESSING_OR_FETCHED": "Failed to create delivery because a previously created delivery for this product is currently being delivered to {0}. This is an edge case, please try again in a few moments",
    "FEEDBACK_REQUIRED": "Feedback is required.",
    "FIELD_NOT_VALID_URL": "url not valid.",
    "FIELD_REQUIRED": "The following field(s) are required: {0}. Please fill them in and try again.",
    "FIELD_TOO_LONG": "Field {0} was too long for: {1}.",
    "FIELD_UNIQUE": "The fields {0} and {1} may not have the same value (value is now {2} for both).",
    "FIELD_VALUE_NOT_IN_LIST": "Invalid value ''{0}'' for {1}. Allowable values are: {2}",
    "FIELD_VALUE_NOT_IN_RANGE": "Invalid value ({0}) for {1}: allowed values are between {2} and {3}",
    "FIELD_VALUE_WRONG": "Invalid value: {0}",
    "FILE_DURATION_NOT_SAME": "Duration of the uploaded encoding does not match duration of other encoding(s) of this track",
    "GENRE_NOT_FOUND": "No genre with name {0} was found",
    "HASH_MATCH_FAILED": "You are not authorized to use that invitation.",
    "HD_VIDEO_BITRATE_MUST_BE_AT_LEAST_80_MBIT": "HD videos' bitrate must be at least 80 Mbit",
    "IDENTIFIER_NOT_SUPPORTED": "This type of identifiers is not supported by {0}",
    "IGT_DOES_NOT_ALLOW_TERRITORY_RESTRICTIONS": "Track level territories are not allowed on Instant Gratification tracks ({0})",
    "INCOMPLETE_WORK_ON_PRODUCT": "Not all movements of work {0} are present on this product.",
    "INCORRECT_QUALITY_LEVEL": "The quality of the uploaded file did not match the expected quality.",
    "INCORRECT_TAG_CATEGORY": "The category type of this Tag is incorrect.",
    "INVALID_ACQUISITION_TYPE": "Invalid acquisition type change: {0}.",
    "INVALID_BOOLEAN": "Excepted a boolean value (true or false) for field {0}. You now passed {1}",
    "INVALID_DATE": "The provided date is invalid.",
    "INVALID_DIMENSIONS": "Cover art dimensions must be at least 1400x1400",
    "INVALID_DOLBY_ATMOS_FILE": "Invalid file: A 24-bit LPCM at 48 kHz file is required for Dolby Atmos",
    "INVALID_EMAIL_ADDRESS": "The email address is invalid.",
    "INVALID_INTEGER": "Excepted an integer value number (such as 1, 2 or 3) for field {0}. You now passed {1}",
    "INVALID_ITUNES_CONVERSION_STATE_TRANSITION": "The iTunes Conversion state could not be changed.",
    "INVALID_LABEL_ID": "The provided label id is invalid.",
    "INVALID_NUMBER": "The number is invalid. {0}",
    "INVALID_NUMBER_OF_DAYS": "Number of days is invalid.",
    "INVALID_NUMBER_OF_DOWNLOADS_AND_NUMBER_OF_STREAMS": "Both the number of downloads and the number of streams are invalid.",
    "INVALID_NUMBER_OF_ENTRIES": "The number of entries is invalid.",
    "INVALID_NUMBER_OF_LABELS": "The number of labels is invalid.",
    "INVALID_NUMBER_OF_RESULTS": "The number of requested results is invalid.",
    "INVALID_ORGANIZATION_ID": "The provided organization id is invalid.",
    "INVALID_ORGANIZATION_REQUEST_STATE_TRANSITION": "Organization status cannot be changed to {0}.",
    "INVALID_PARAMETER": "The provided parameter is invalid.",
    "INVALID_PASSWORD": "Password is invalid. Your password should be at least 6 characters long.",
    "INVALID_PRODUCT_AND_ASSET": "Product and asset are both invalid.",
    "INVALID_RECEIPT": "Upload processing was unsuccessful.",
    "INVALID_REDELIVER_BULK_OPERATION": "Cannot create auto-cancel redelivery bulk operation.",
    "INVALID_RELEASE_STATE_TRANSITION": "The release state could not be changed.",
    "INVALID_SAMPLING_RATE": "{0} does not support {1} bit depth audio",
    "INVALID_SEARCH_QUERY": "The search query is invalid.",
    "INVALID_STATE_CHANGE": "Invalid state change. {0}",
    "INVALID_STATUS": "Invalid status. {0}",
    "INVALID_STRING": "Invalid value detected, cannot save entity {0}",
    "INVALID_TERRITORY": "The provided territory is invalid.",
    "INVALID_TERRITORY_FOR_DELIVERY_PROCESS": "The territory set is not allowed for this delivery party",
    "INVALID_TIER_FOR_DELIVERY_PROCESS": "The tier set is not allowed for this delivery party",
    "INVALID_VALUE": "Cannot write value {0} to field {1}. Expected {2}.",
    "INVALID_VOLUME": "Asset volume cannot be greater than the total number of discs.",
    "ISRC_POOL_DEPLETED": "There are no more available ISRCs, please contact our support team",
    "LABEL_IDENTIFIERS_NOT_ALLOWED": "Label Identifier feature is not enabled for this organization. Please contact your account manager to have it enabled.",
    "LABEL_IDENTIFIERS_NOT_SUPPORTED": "Label identifiers are not supported by {0}.",
    "LABEL_INVALID_IDENTIFIER": "The provided DSP Label Identifier does not have the correct format. {0}",
    "LABEL_NOT_FOUND": "No label found: {0}.",
    "LINKED_CATALOG_NUMBER_NOT_FOUND": "Product with this Catalog Number doesn't exist",
    "LOCALIZATION_DISALLOWED_CHARACTERS": "The localization cannot be saved. The following characters are invalid: {0}",
    "LYRICS_ARE_REQUIRED": "Lyrics are required for delivering.",
    "MAIL_ERROR": "There was a problem with the Mail Service.",
    "MISSING_NEIGHBOURING_RIGHTS_CONTRIBUTORS": "At least one featuring and one non-featuring contributors are required.",
    "MORE_THAN_ONE_RESULT": "Found more than one result.",
    "MULTIPLE_ARTISTS_FOUND": 'Found multiple artists with the name "{0}". Please provide a proprietary ID to narrow results down to one. Possible values: {1}.',
    "MULTIPLE_EMAIL_ADDRESSES": "A problem occurred while trying to reset the password for email address: {0}. Please contact our support team.",
    "MUST_BE_AN_ORGANIZATION_REQUEST": "Only Organization Requests have vault items of type document. Make sure you pass the ID of the right entity.",
    "MUST_BE_ATTACHMENT_OR_CONTRACT": "Only Contracts and Attachments have vault items of type attachment. Make sure you pass the ID of the right entity.",
    "MUST_HAVE_PUBLISHING_HOUSE_WITHOUT_COPYRIGHT_CONTROL": "Without copyright control, a publisher is required.",
    "MUST_HAVE_TRACK": "A track must be supplied.",
    "MUST_NOT_INCLUDE_WORLD": "Territory world is not allowed.",
    "NO_BARCODE_POOL_FOUND_FOR_ORGANIZATION": "Organization with ID {0} does not have a barcode pool attached",
    "NO_CONTRACT_FOUND_FOR_ORGANIZATION_AND_DSP_NAME": "No Contract was found for the provided Organization and DSP name.",
    "NO_ERROR_MESSAGE": "No error message was provided.",
    "NO_IP_ADDRESS": "An IP address must conform to the following pattern: {0}",
    "NO_IP_SUBNET": "The IP subnet {1} must conform to the following pattern: {0}",
    "NO_ISRC_POOL_FOUND_FOR_ORGANIZATION": "Organization does not have an ISRC pool configured",
    "NO_LIVELINK_FOUND": "Links are not available for this combination of issuing organization and entity",
    "NO_PRICE_ALLOWED_FOR_DELIVERY_PROCESS": "No price can be set for this delivery party",
    "NO_PRICE_ALLOWED_FOR_WORLD": "No price can be set for World",
    "NO_RIGHTS_ADDED": "No rights could be accepted for this invitation.  Permitted rights are {0}.",
    "NO_SUPER_ORG": "This organization has no white label functionality",
    "NOT_A_DIRECT_TAG": "The specified tag is not a direct tag.",
    "NOT_A_NUMBER": "({0}) is not a number.",
    "NOT_AUTHORIZED": "You are not authorized to perform that operation.",
    "NOT_BLANK": "Must not be blank!",
    "NOT_FOUND": "What you were looking for could not be found. See below for details.",
    "NOT_LOGGED_IN": "You are currently not logged in and therefore cannot make use of the system. Please log in first.",
    "NOT_OWNED_TAG": "Could not use the tag, because it is owned by another organization.",
    "NUMBER_OF_DOWNLOADS_AND_NUMBER_OF_STREAMS_ARE_BOTH_MISSING": "Number of downloads and number of streams are both missing.",
    "NUMBER_OF_DOWNLOADS_MUST_BE_A_POSITIVE_VALUE": "Number of downloads must be a positive value. Zero included.",
    "NUMBER_OF_STREAMS_MUST_BE_A_POSITIVE_VALUE": "Number of streams must be a positive value. Zero included.",
    "ONE_OF_THE_FOLLOWING_IS_REQUIRED": "One of the following fields must be passed: {0}.",
    "ONLY_EFFECTIVE_CONTRACTS_MAY_BE_EXPIRED": "A contract must be in effective state for it to be expired",
    "ONLY_EXPIRED_CONTRACTS_MAY_BE_MADE_PENDING": "A contract must be in expired state for it to be made pending",
    "ONLY_PENDING_CONTRACTS_MAY_BE_MADE_EFFECTIVE": "A contract must be in pending state for it to be made effective",
    "OPERATION_FORBIDDEN": "The requested action cannot be processed. Please contact support",
    "ORGANIZATION_ALREADY_HAS_EMPLOYEE": "The organization already has this employee",
    "ORGANIZATION_CANNOT_BE_BOUND_TO_SELF": "You are trying to become a contact to your own organization. Make sure that the organization you want to become your contact logs into the system after following the email link, instead of yourself",
    "ORGANIZATION_FEATURE_BARCODE_DISABLED": "Automatic Barcode Assignment feature is not enabled for this organization",
    "ORGANIZATION_FEATURE_DISABLED": "The feature is disabled for this organization",
    "ORGANIZATION_MUST_HAVE_SUPER_CAPABILITY": "The organization must be able to pose as a super organization",
    "ORGANIZATION_NOT_FOUND": "The organization with the passed ID could not be found",
    "ORGANIZATION_REQUEST_ALREADY_CONFIRMED": "The request has already been promoted and cannot be promoted again",
    "ORGANIZATION_REQUEST_ALREADY_PROCESSED": "The request has already been processed and cannot be processed again",
    "ORGANIZATION_REQUEST_ALREADY_SUBMITTED": "The request has already been submitted and cannot be re-submitted",
    "ORGANIZATION_REQUEST_CONFIRMED_REQUIRES_USER": "A confirmed organization request requires an associated user",
    "ORGANIZATION_REQUEST_MUST_CONTAIN_USER_REQUEST": "There must be at least one user to submit your signup form",
    "ORGANIZATION_REQUEST_NEEDS_TO_BE_CONFIRMED_BEFORE_PROCESSING": "The request needs to be confirmed first before it can be processed",
    "ORGANIZATION_REQUEST_NEEDS_TO_BE_SUBMITTED_BEFORE_CONFIRMATION": "The request needs to be submitted first before it can be promoted",
    "ORIGINAL_ENCODING_DOLBY_ISRC_NOT_UNIQUE": "Dolby Atmos ISRC must be unique across asset catalog",
    "ORIGINAL_RELEASE_SHOULD_BE_EQUAL_OR_BEFORE_CONSUMER_RELEASE_DATE": "Original release date should be equal or before the consumer release date",
    "PARAMETER_MISSING": "A parameter was missing from the request: {0}.",
    "PARENT_REQUIRED": "A VaultItem cannot exist without a parent.",
    "PREORDERDATE_MUST_PRECEDE_RELEASEDATE": "The Pre-order date must occur before the release date.",
    "PREVIEW_SETTINGS_INVALID": "The combination of preview length and preview start is longer than the duration of this asset.",
    "PRICE_OR_CATALOG_TIER_REQUIRED": "A price or catalog tier is required.",
    "PRICING_INTERVAL_END_DATE_BEFORE_RELEASE_DATE": "The end date of a pricing interval cannot be before the release date",
    "PRICING_INTERVALS_OVERLAP": "No pricing intervals can overlap",
    "PRODUCT_ALREADY_HAS_UPC": "Product already has a barcode assigned",
    "PRODUCT_AND_ASSET_ARE_BOTH_MISSING": "Product and Asset are both missing. At least one of them should be provided.",
    "PRODUCT_AND_ASSET_NOT_LINKED": "Product {0} and Asset {1} are not linked.",
    "PRODUCT_CAN_ONLY_BE_SOURCED_BY_UPSTREAM_ORGANIZATION": "The product can only be sourced by the upstream organization.",
    "PRODUCT_CANNOT_BE_FOUND": "No product with an ID of {0} could be found.",
    "PRODUCT_CANNOT_BE_SOURCED_ALREADY_SCHEDULED": "The product cannot be sourced because it has already been scheduled.",
    "PRODUCT_DOES_NOT_CONTAIN_ASSET": "Product {0} is not attached to Asset {1}.",
    "PRODUCT_DOES_NOT_EXIST": "A required product does not exist",
    "PRODUCT_DOES_NOT_HAVE_A_DEFAULT_RELEASE_SCHEDULE": "The product does not have a default release schedule",
    "PRODUCT_HAS_BEEN_DELETED": "The product related to this release schedule has already been deleted",
    "PRODUCT_HAS_BEEN_DELIVERED_BY_OTHER_PARTY": "A duplicate product (title {0}, version {1}, catalog number {2}) has been delivered to {3} by another distributing party in overlapping territories. Please contact support for more information.",
    "PRODUCT_HAS_BEEN_DELIVERED_BY_OTHER_PARTY_SAME_UPC": "{0} has been delivered to {1} by another distributing party in overlapping territories. Please contact support for more information.",
    "PRODUCT_HAS_NO_PARENT": "This product has no parent",
    "PRODUCT_IS_NOT_SOURCED": "The product has no parent product. Check whether the product is really sourced",
    "PRODUCT_MARKED_AS_EXPLICIT_BUT_NO_EXPLICIT_ASSETS": "Product with UPC {0} is explicit but there are no explicit assets.",
    "PRODUCT_MUST_NOT_HAVE_ONLY_PREORDER_ASSETS": "Product cannot only consist of preorder-only assets.",
    "PRODUCT_NAME_AND_ASSET_NAME_ARE_BOTH_MISSING": "Product name and asset name are both missing.",
    "PUBLISHERS_ARE_REQUIRED": "Composer information is required.",
    "PUBLISHING_PRODUCT_WITHOUT_LATCHED_DELIVERY_RULE_SETS": "The status of the product cannot be set to PUBLISHED since it has no latched delivery rule set.",
    "RANGE": "Must be between {2} and {1}",
    "RELEASE_DATE_REQUIRED": "Both the Consumer Release Date and schedule Release Date must be supplied.",
    "RELEASE_SCHEDULE_DOES_NOT_HAVE_A_PRODUCT": "The release schedule does not apply to an existing product",
    "RELEASE_SCHEDULE_REQUIRED_FOR_DELIVERY": "To create a delivery, a release schedule is required.",
    "REPORT_LINE_REQUIRED": "Report line required",
    "REQUEST_CONTEXT_IS_MISSING_A_USER_AND_OR_ORGANIZATION": "RequestContext is missing a User and/or an Organization.",
    "REQUEST_CONTEXT_IS_MISSING_AN_ORGANIZATION": "RequestContext is missing an Organization.",
    "RULE_SET_NEEDS_DEFAULT_MAPPING": "A rule set needs a mapping with no criteria",
    "RULE_SET_NEEDS_TIER_SETS": "A rule set needs at least a product tier set",
    "RULE_SET_NOT_READY": "Rule set not ready for use",
    "RULE_SET_ONLY_PRICES_NEEDS_COMPLETE_MAPPINGS": "A rule set with a tier set that has no tiers, just prices, needs complete mappings for the default rule",
    "SEARCH_PHRASE_NOT_COMPLETELY_DOUBLE_QUOTED": "Make sure your search phrase is captured in double quotes",
    "SELLABLE_ITEM_NOT_FOUND": "No Asset or product with an ID of {0} could be found.",
    "SERVER_UNABLE_TO_COMPLETE_REQUEST": "The server was unable to complete your request.",
    "SERVICE_UNAVAILABLE": "Service, {0}, temporarily unavailable, please try again later.",
    "SIMILAR_ARTIST_NAME": "{0} already has an Artist with the same (normalized) name attached to it.",
    "STARTDATE_SHOULD_PRECEDE_ENDDATE": "The start date should precede the end date",
    "SUB_ORG_NOT_OWNED": "The sub-organization does not belong to you",
    "SYSTEM_USER_FROM_ILLEGAL_IP_RANGE": "System user {0} logs in from {1} which is outside the whitelisted IP range",
    "TAG_NOT_FOUND": "The tag with the passed ID could not be found",
    "TERRITORIES_DO_NOT_INTERSECT": "The territories in the contract to {0} do not allow distribution of this product.",
    "TERRITORIES_MISSING": "At least 1 territory must be specified.",
    "TERRITORY_ALREADY_USED_IN_SCHEDULE": "The territory {0} was already used in set {1}.",
    "TERRITORY_EXCEPTION_ONLY_ALLOWED_ON_DEFAULT_RELEASE_SCHEDULE": "Territory exception can only be tied to the default release schedule.",
    "TOKEN_REQUIRED": "The search string was terminated unexpectedly",
    "TOO_MANY_PRODUCTS_TO_TAG": "The number of tagged products is too high",
    "TOO_MANY_SEARCH_RESULTS": "The query returned too many results, please narrow your search",
    "TRACK_RELEASE_DATE_OUTSIDE_IGT_RANGE": "The release date of the Instant Grat track with ISRC {0} is not between the pre-order date and the release date",
    "TRANSLATION_CANNOT_SAVE_INVALID_FIELD": "Cannot save translation, given field is not valid",
    "TRANSLATION_REQUIRED": "{0} translation is required for ''{1}''",
    "UNDEFINED": "System error. Please consult operational support at IndependentIP",
    "UNDEFINED_COMMAND": "The email invitation you tried to redeem is not recognized by the system as legitimate.",
    "UNEXPECTED_RESULT": "Unexpected result: {0}",
    "UNSUPPORTED_SEARCH_PROPERTY": "A property or field specified in the search query is not supported: {0}.",
    "UPC_AND_ISRC_ARE_BOTH_MISSING": "UPC and ISRC are both missing.",
    "UPC_CODE_WRONG": "UPC code {0} does not validate!",
    "UPDATE_FAILED": "Update failed.",
    "UPDATE_TRACK_ORDER_NOT_ALLOWED": "The track order cannot be changed after a product has been approved.",
    "UPSTREAM_DOWNSTREAM_REQUIRED": "You must specify either an up or downstream organization.",
    "USER_ACCOUNT_SUSPENDED": "Account temporarily disabled",
    "USER_ALREADY_EMPLOYED": "User is already an employee of another organization.",
    "USER_CANNOT_BE_BOUND_TO_SELF": "You are trying to become a contact to yourself. Make sure that the user you want to become your contact logs into the system after following the email link, instead of yourself.",
    "USER_NOT_AUTHORIZED_FOR_CONTACT": "You are not authorized to edit this contact.",
    "USER_NOT_AUTHORIZED_FOR_DEAL": "You are not authorized to edit this deal.",
    "USER_NOT_EMPLOYED": "The user with passed ID is not employed.",
    "USER_NOT_FOUND": "The user with passed ID could not be found.",
    "USER_OR_PASSWORD_INCORRECT": "You entered a wrong username and/or password. Please retry with your correct username/password.",
    "VALIDATION_FAILED": "Validation failed.",
    "VALUE_NOT_ALLOWED": "Value not allowed.",
    "VAULT_ITEM_NOT_FOUND": "Vault Item with ID {0} could not be found.",
    "CANNOT_DELETE_DELIVERED_MOTION_ART": "Motion Art file cannot be deleted because it was delivered.",
    "CONTRACT_ORGANIZATIONS_MUST_BE_DIFFERENT": "A contract has the same organization (id: {0}) set for the upstream and downstream organizations.",
    "TOO_MANY_CODES_REQUESTED": "Too many codes requested, please specify a number no larger than {0}",
    "PREVIEW_DATE_BEFORE_RELEASE_DATE": "Preview date must be before the release dates of both the product and the asset.",
    "WEAK_PASSWORD": "<ul> <li>- Password must be 12 characters minimum</li> <li>- Password must contain at least one alphabetical character</li> <li>- Password must contain at least one digit (0-9)</li> <li>- Password must contain at least one special character (!@#$%^&*_+-,.')</li> </ul> ",
    "PASSWORD_CANNOT_BE_SAME": "The new password can not be the same as the previous one",
    "true": "An unexpected error occurred, please contact your administrator",
    "USER_2FA_ALREADY_ENABLED": "User Already has an active 2FA",
    "USER_TWO_FACTOR_AUTHENTICATION_ALREADY_ENABLED": "User already has an active Two-Factor Authentication",
    "USER_TWO_FACTOR_AUTHENTICATION_NOT_CONFIGURED": "Two-Factor Authentication is not configured for the user",
    "USER_TWO_FACTOR_AUTHENTICATION_INVALID_TOTP": "Invalid Time Based One Time Password",
    "USER_TWO_FACTOR_AUTHENTICATION_MISSING_FIRST_STEP": "The first step of the authentication process not done yet",
    "USER_TWO_FACTOR_AUTHENTICATION_INVALID_BACKUP_CODE": "Invalid Backup Code",
    "DUPLICATE_PROJECT_NAME": "Release Project with name {0} already exist in Organization with ID {1}",
    "PRODUCT_ALREADY_IN_ANOTHER_RELEASE_PROJECT": "One or more products are already in other release projects and can not be added to this release project",
    "PRE_ORDER_ONLY_TRACKS_MUST_BE_AT_THE_END_OF_TRACK_LIST": "Tracks cannot be placed after Pre-Order Only tracks. Ensure Pre-Order Only tracks are at the end of the tracklist",
    "CREATING_DIRECT_CHANNELS_OF_THE_TYPE_ARE_NOT_ALLOWED": "Creating Channels of the requested type are not allowed, use the intended workflow for that",
    "INVALID_ASSET_TYPE_FOR_CHANNEL_DATA": "Channel data can only be added to Music Video assets",
    "PASSWORD_INCORRECT": "The password is incorrect",
    "INVITATION_NOT_FOUND": "The invitation is no longer valid.",
    "REQUEST_EXPIRED": "This request has expired.",
    "PRODUCT_ALREADY_IN_SUB_ORGANIZATION": "Product ({0}) is already present in the target sub organization {1}",
    "BULK_OPERATION_INVALID_REDELIVER_WITH_OVERRIDE": "The delivery status override feature can't be used in combination with the redelivery feature.",
    "FIELDS_MIXED_EMPTY_AND_NON_EMPTY": "All fields must either be empty or filled.",
    "INVALID_DOMAIN_FOR_USER_EMAIL": "Email address is not associated with an approved domain.",
    "DUPLICATE_USERNAME": "User with the username {0} already exists. Please choose another username.",
}
